#! /bin/bash

sudo setterm -powerdown 0
#export DISPLAY=:0;
#export XAUTHORITY=:/home/pi/.Xauthority;
sleep 120

sudo xdotool windowactivate "$(xdotool search --class chromium | tail -1)" && xdotool key --window "$(xdotool search --class chromium | tail -1)" F5 
#sudo xdotool key F5
